export const TRACK_EVENT_DATA_PROCESS = 'TRACK_EVENT_DATA_PROCESS'

export const TRACK_EVENT_QUEUE_MANAGER = 'TRACK_EVENT_QUEUE_MANAGER'

export const EVENT_CENTER = 'EVENT_CENTER'

export const PAGE_LIFECYCLE_TRACK = 'PAGE_LIFECYCLE_TRACK'

export const CONFIG_STORE = 'CONFIG_STORE'

export const EVENT_STORE = 'EVENT_STORE'
