export const EVENT_CONFIG_IS_EMPTY = 'EVENT_CONFIG_IS_EMPTY'

export const UNKNOWN_EVENT_TYPE = 'UNKNOWN_EVENT_TYPE'

export const EVENT_NAME_IS_NOR_REGISTER = 'EVENT_NAME_IS_NOR_REGISTER'

export const EVENT_NAME_IS_EMPTY = 'EVENT_NAME_IS_EMPTY'

export const HOOK_NAME_IS_EMPTY = 'HOOK_NAME_IS_EMPTY'

export const HOOK_CALLBACK_IS_EMPTY = 'HOOK_CALLBACK_IS_EMPTY'
